tokenizer: "roberta-base"
classname: "TextClozeTextOnlyRobertaModel"

num_tokens: 32100
dropout: 0.4
encoder_size: 768

answer_candidates: 3
answer_max_tokens: 30

context_panels: 3
context_max_boxes_size: 3
context_max_speech_size: 30
pooler_size: 256

metrics:
  - accuracy