tokenizer: "t5-base"
architecture: "t5-base"
classname: "TextClozeImageTextT5Model"

num_tokens: 32100
answer_candidates: 3

max_length: 768
image_embedding_size: 2048
embedding_size: 768
encoder_size: 768

pooler_size: 256
dropout: 0.05
dropout_p: 0.005

metrics:
  - accuracy