tokenizer: "t5-base"
architecture: "t5-base"
classname: "TextClozeTextOnlyT5Model"

num_tokens: 32100
answer_candidates: 3

max_length: 768
embedding_size: 768
encoder_size: 768

# pooler_size: 256
pooler_size: 256
dropout: 0
dropout_p: 0

metrics:
  - accuracy