epochs: 10
runs_path: "./runs/"
report_path: "./reports/"

optimizer:
  type: "adafactor" 
  gradient_accumulation_steps: 1
  scale_parameter: True
  relative_step: True
  warmup_init: True
  clip_threshold: True