name: "comics_dialogue_generation_with_posible_answers"
mode: "hard_context_textract"
panels_features_path: "/data/data/datasets/COMICS/Sim_CLR_panels_features/Sim_CLR_panels_features.pkl"
answer_max_tokens: 30
context_max_speech_size: 30
n_boxes: 1
max_text_length: 400
gen_max_length: 30
num_answers: 3
