name: "text_cloze_image_text_vlt5"
mode: "hard"
panel_features_path: "/data/data/datasets/COMICS/test_bb_SAM_ofuscate.hdf5"
answer_max_tokens: 30
context_max_speech_size: 30
n_boxes: 36
max_text_length: 400
gen_max_length: 2