name: "text_cloze_image_text_vlt5_BLIP2_not_masked_context_not_context_text_input"
mode: "easy_context_textract"
panels_features_answer_path: "/data/data/datasets/COMICS/Sim_CLR_panels_features/Sim_CLR_panels_features.pkl"
panels_features_context_path: "/data/data/datasets/COMICS/Sim_CLR_panels_features/Sim_CLR_panels_features_not_masked.pkl"
num_answers: 3
answer_max_tokens: 30
context_max_speech_size: 30
n_boxes: 1
max_text_length: 400
gen_max_length: 2