name: "comics_images_Sim_CLR_text"
mode: "easy"

path_SIM_CLR_model: "/home/jlafuente/ComicsQA/Models/test_model_25_epochs_730k_img.pt"
panels_features_path: "/data/data/datasets/COMICS/Sim_CLR_panels_features/Sim_CLR_panels_features.pkl"
# panels_features_path: "/home/jlafuente/ComicsQA/Datasets/comics/Sim_CLR_panels_features/Sim_CLR_panels_features.pkl"
answer_max_tokens: 30
context_max_speech_size: 30